### ISSUE TITLE
bootstrap for genes

### ISSUE THREAD

**Issue by Dokmen** [tpepler/nonpar#1]
Hi,
I used this function for my microarray data set.  In the gene expression matrix, rows contain genes and columns contain samples. There are 10[1:10] controls and 10[11:20] treatment samples. I want to compare each genes between two groups and use the two sample t-test. I changed your function for gene exp. matrix. 

ExpMatrix sample is that:

![Gene-expression-matrix](https://user-images.githubusercontent.com/40204216/110531637-dd85a700-812c-11eb-90e1-ab7e29e00d33.png) 

`boot.t.test <- function(x, y, reps = reps, alternative = c("two.sided", "less", "greater")){
x <- ExpMatrix[11:20]
y <- ExpMatrix[1:10]
  nx <- length(x)
  ny <- length(y)
  t.obs <- apply(x, 1, mean) - apply(y, 1, mean)  / sqrt(apply(x, 1, var) / nx + apply(y, 1, var) / ny)
  comb.mean <- apply(ExpMatrix, 1, mean) 
  x.c <- x - apply(x, 1, mean) + comb.mean
  y.c <- y - apply(y, 1, mean) + comb.mean
  
}
   bootFunc <- function(){
    bootx <- x.c[sample(1:nrow(x.c), size = nrow(x.c), replace = TRUE),]
    booty <- y.c[sample(1:nrow(y.c), size = nrow(y.c), replace = TRUE),]
    apply(bootx, 1, mean) - apply(booty, 1, mean)/ sqrt(apply(bootx, 1, var) / nx + apply(booty, 1, var) / ny)
   
  }
  
   t.boot <- replicate(reps, expr = bootFunc())
  
  if(alternative[1] == "two.sided"){
    pval <- length(t.boot[abs(t.boot) >= abs(tobs)]) / reps
    h1phrase <- "not equal to"
  }`

This function is running. But I could not run pval for each row. Can you help me? Can pval codes above convert to" "apply" function for each row?

**Comment by tpepler** [comment]
Perhaps you can just change the first couple of lines of boot.t.test (the original version) like this:

boot.t.test <- function(x, reps = reps, alternative = c("two.sided", "less", "greater")){
x <- x[11:20]
y <- x[1:10]

Further change the last statement of boot.t.test to:

return(p.value = pval)

so it only returns the p-value, and then run this modified function on the rows of ExpMatrix:

apply(ExpMatrix, 1, boot.t.test, reps = ..., alternative = ...)

That should return a vector of p-values for the rows (genes) in ExpMatrix.

Let me know if that does what you want?

Regards

Theo

**Comment by Dokmen** [comment]
Dear Professor,
Thank you for your response. I run the code in this way. Thank you very much.
I wrote some more functions for bootstrap and will do a comparative analysis with both your package and other packages. Your function run faster than the boot package. However, the results are quite different from the results obtained in the boot package. At least I should have had similar results. I'm a researcher in covid-19 project. Can I contact you later by e-mail?

**Comment by tpepler** [comment]
Yes, you are welcome to contact me by e-mail (theo.pepler@glasgow.ac.uk).
You should get similar results if doing the same thing with different packages. We should try to find out what causes these differences.
Regards
Theo
